# Joining and Splitting Arrays
- concatenate
- stack
- split


In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b

array([[5, 6]])

In [5]:
together = np.concatenate((a,b), axis=0)

In [6]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
together.shape

(3, 2)

In [8]:
together[1,1] = 555

In [9]:
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [12]:
c = np.array([[1,2],[3,4]])*3+5
c

array([[ 8, 11],
       [14, 17]])

In [14]:
np.concatenate((a,c),axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [15]:
arrays= np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3,4)
arrays

array([[[ 0.99799711,  0.49748989,  1.10215943,  0.05263983],
        [ 0.87987223,  0.3190431 , -2.0829436 , -0.5007715 ],
        [-0.79515694, -0.29719899, -0.9104636 , -0.63306455]],

       [[ 0.59255563, -0.64049522, -0.89135112,  0.4778354 ],
        [-2.09170493, -0.19763932,  1.26672971,  2.49444303],
        [-0.73220436, -0.63600603,  0.55850056, -1.73674516]],

       [[-2.13515079, -1.26969949, -0.35031746,  0.36697678],
        [-1.03166547,  0.1538131 , -0.21968336, -0.12596854],
        [-0.17174961,  0.5142394 , -0.27296494, -1.48228995]],

       [[ 0.50434224, -1.91341844,  1.16662839, -0.8324204 ],
        [-2.13466868, -0.77657349, -0.97101102,  0.64545251],
        [-0.73667192, -0.58673213, -1.33384273,  0.17074187]],

       [[-0.96474271,  0.36889067,  0.4632624 ,  1.84858276],
        [ 0.02127107,  0.27837976,  1.36073706, -0.74283847],
        [ 0.76215168,  0.3724816 ,  0.47029905,  1.09141112]]])

In [16]:
stack0 =np.stack(arrays, axis=0)
stack1 =np.stack(arrays, axis=1)
stack2 =np.stack(arrays, axis=2)

In [17]:
stack0

array([[[ 0.99799711,  0.49748989,  1.10215943,  0.05263983],
        [ 0.87987223,  0.3190431 , -2.0829436 , -0.5007715 ],
        [-0.79515694, -0.29719899, -0.9104636 , -0.63306455]],

       [[ 0.59255563, -0.64049522, -0.89135112,  0.4778354 ],
        [-2.09170493, -0.19763932,  1.26672971,  2.49444303],
        [-0.73220436, -0.63600603,  0.55850056, -1.73674516]],

       [[-2.13515079, -1.26969949, -0.35031746,  0.36697678],
        [-1.03166547,  0.1538131 , -0.21968336, -0.12596854],
        [-0.17174961,  0.5142394 , -0.27296494, -1.48228995]],

       [[ 0.50434224, -1.91341844,  1.16662839, -0.8324204 ],
        [-2.13466868, -0.77657349, -0.97101102,  0.64545251],
        [-0.73667192, -0.58673213, -1.33384273,  0.17074187]],

       [[-0.96474271,  0.36889067,  0.4632624 ,  1.84858276],
        [ 0.02127107,  0.27837976,  1.36073706, -0.74283847],
        [ 0.76215168,  0.3724816 ,  0.47029905,  1.09141112]]])

In [18]:
stack1

array([[[ 0.99799711,  0.49748989,  1.10215943,  0.05263983],
        [ 0.59255563, -0.64049522, -0.89135112,  0.4778354 ],
        [-2.13515079, -1.26969949, -0.35031746,  0.36697678],
        [ 0.50434224, -1.91341844,  1.16662839, -0.8324204 ],
        [-0.96474271,  0.36889067,  0.4632624 ,  1.84858276]],

       [[ 0.87987223,  0.3190431 , -2.0829436 , -0.5007715 ],
        [-2.09170493, -0.19763932,  1.26672971,  2.49444303],
        [-1.03166547,  0.1538131 , -0.21968336, -0.12596854],
        [-2.13466868, -0.77657349, -0.97101102,  0.64545251],
        [ 0.02127107,  0.27837976,  1.36073706, -0.74283847]],

       [[-0.79515694, -0.29719899, -0.9104636 , -0.63306455],
        [-0.73220436, -0.63600603,  0.55850056, -1.73674516],
        [-0.17174961,  0.5142394 , -0.27296494, -1.48228995],
        [-0.73667192, -0.58673213, -1.33384273,  0.17074187],
        [ 0.76215168,  0.3724816 ,  0.47029905,  1.09141112]]])

In [19]:
stack2

array([[[ 0.99799711,  0.59255563, -2.13515079,  0.50434224,
         -0.96474271],
        [ 0.49748989, -0.64049522, -1.26969949, -1.91341844,
          0.36889067],
        [ 1.10215943, -0.89135112, -0.35031746,  1.16662839,
          0.4632624 ],
        [ 0.05263983,  0.4778354 ,  0.36697678, -0.8324204 ,
          1.84858276]],

       [[ 0.87987223, -2.09170493, -1.03166547, -2.13466868,
          0.02127107],
        [ 0.3190431 , -0.19763932,  0.1538131 , -0.77657349,
          0.27837976],
        [-2.0829436 ,  1.26672971, -0.21968336, -0.97101102,
          1.36073706],
        [-0.5007715 ,  2.49444303, -0.12596854,  0.64545251,
         -0.74283847]],

       [[-0.79515694, -0.73220436, -0.17174961, -0.73667192,
          0.76215168],
        [-0.29719899, -0.63600603,  0.5142394 , -0.58673213,
          0.3724816 ],
        [-0.9104636 ,  0.55850056, -0.27296494, -1.33384273,
          0.47029905],
        [-0.63306455, -1.73674516, -1.48228995,  0.17074187,
          1

In [20]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [21]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [22]:
s0=np.split(before_split, 5, axis=0)
s0

[array([[[ 0.99799711,  0.49748989,  1.10215943,  0.05263983],
         [ 0.87987223,  0.3190431 , -2.0829436 , -0.5007715 ],
         [-0.79515694, -0.29719899, -0.9104636 , -0.63306455]]]),
 array([[[ 0.59255563, -0.64049522, -0.89135112,  0.4778354 ],
         [-2.09170493, -0.19763932,  1.26672971,  2.49444303],
         [-0.73220436, -0.63600603,  0.55850056, -1.73674516]]]),
 array([[[-2.13515079, -1.26969949, -0.35031746,  0.36697678],
         [-1.03166547,  0.1538131 , -0.21968336, -0.12596854],
         [-0.17174961,  0.5142394 , -0.27296494, -1.48228995]]]),
 array([[[ 0.50434224, -1.91341844,  1.16662839, -0.8324204 ],
         [-2.13466868, -0.77657349, -0.97101102,  0.64545251],
         [-0.73667192, -0.58673213, -1.33384273,  0.17074187]]]),
 array([[[-0.96474271,  0.36889067,  0.4632624 ,  1.84858276],
         [ 0.02127107,  0.27837976,  1.36073706, -0.74283847],
         [ 0.76215168,  0.3724816 ,  0.47029905,  1.09141112]]])]

In [23]:
type(s0)

list

In [24]:
s0[1]

array([[[ 0.59255563, -0.64049522, -0.89135112,  0.4778354 ],
        [-2.09170493, -0.19763932,  1.26672971,  2.49444303],
        [-0.73220436, -0.63600603,  0.55850056, -1.73674516]]])

In [25]:
s0[1].shape

(1, 3, 4)

In [26]:
s1=np.split(before_split, 3, axis=1)
s1

[array([[[ 0.99799711,  0.49748989,  1.10215943,  0.05263983]],
 
        [[ 0.59255563, -0.64049522, -0.89135112,  0.4778354 ]],
 
        [[-2.13515079, -1.26969949, -0.35031746,  0.36697678]],
 
        [[ 0.50434224, -1.91341844,  1.16662839, -0.8324204 ]],
 
        [[-0.96474271,  0.36889067,  0.4632624 ,  1.84858276]]]),
 array([[[ 0.87987223,  0.3190431 , -2.0829436 , -0.5007715 ]],
 
        [[-2.09170493, -0.19763932,  1.26672971,  2.49444303]],
 
        [[-1.03166547,  0.1538131 , -0.21968336, -0.12596854]],
 
        [[-2.13466868, -0.77657349, -0.97101102,  0.64545251]],
 
        [[ 0.02127107,  0.27837976,  1.36073706, -0.74283847]]]),
 array([[[-0.79515694, -0.29719899, -0.9104636 , -0.63306455]],
 
        [[-0.73220436, -0.63600603,  0.55850056, -1.73674516]],
 
        [[-0.17174961,  0.5142394 , -0.27296494, -1.48228995]],
 
        [[-0.73667192, -0.58673213, -1.33384273,  0.17074187]],
 
        [[ 0.76215168,  0.3724816 ,  0.47029905,  1.09141112]]])]

In [27]:
s2=np.split(before_split, 4, axis=2)
s2

[array([[[ 0.99799711],
         [ 0.87987223],
         [-0.79515694]],
 
        [[ 0.59255563],
         [-2.09170493],
         [-0.73220436]],
 
        [[-2.13515079],
         [-1.03166547],
         [-0.17174961]],
 
        [[ 0.50434224],
         [-2.13466868],
         [-0.73667192]],
 
        [[-0.96474271],
         [ 0.02127107],
         [ 0.76215168]]]), array([[[ 0.49748989],
         [ 0.3190431 ],
         [-0.29719899]],
 
        [[-0.64049522],
         [-0.19763932],
         [-0.63600603]],
 
        [[-1.26969949],
         [ 0.1538131 ],
         [ 0.5142394 ]],
 
        [[-1.91341844],
         [-0.77657349],
         [-0.58673213]],
 
        [[ 0.36889067],
         [ 0.27837976],
         [ 0.3724816 ]]]), array([[[ 1.10215943],
         [-2.0829436 ],
         [-0.9104636 ]],
 
        [[-0.89135112],
         [ 1.26672971],
         [ 0.55850056]],
 
        [[-0.35031746],
         [-0.21968336],
         [-0.27296494]],
 
        [[ 1.16662839],
   