<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [1]:
import numpy as np

In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
#with start and stop parameters
np.arange(10, 23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [6]:
#counting elements using python method
len(np.arange(10,23))

13

In [7]:
#counting elements using numpy method
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [8]:
np.arange(10, 23).size

13

In [9]:
#start, stop, step
np.arange(10,23,5)

array([10, 15, 20])

In [12]:
#named step
np.arange(0, 26, step=5)

array([ 0,  5, 10, 15, 20, 25])